image: node:latest

stages:
  - test
  - deploy
  
test:
  stage: test
  script:
    - echo 'test'
  tags:
    - cs-518-10
deploy:
  stage: deploy
  before_script:
    - npm config set prefix /usr/local
    - npm install -g serverless
    - serverless plugin install -n serverless-azure-functions
  script:
    - serverless deploy --verbose
  environment: 
    -production
  only:
    - master
  tags:
    - cs-518-10
